import Head from "next/head";
import Layout from "../components/layouts/Article";
import { BiSearch } from "react-icons/bi";
import { HiOutlineEmojiSad } from "react-icons/hi";
import { useEffect, useState } from "react";
import axios from "axios";
import Card from "../components/card/Card";
import { useDispatch, useSelector } from "react-redux";
import { setSearch } from "../redux/features/search/searchSlice";
import FadeLoader from "react-spinners/FadeLoader";
import { setArtist } from "../redux/features/artist/artistSlice";

export default function Home() {
  // const [search, setSearch] = useState("");
  // const [artist, setArtist] = useState(null);
  const [click, setClick] = useState("");
  const [loading, setLoading] = useState(true);

  const search = useSelector((state) => state.search.value);
  const artist = useSelector((state) => state.artist.value);
  // console.log(artist);
  const dispatch = useDispatch();

  useEffect(() => {
    if (artist) {
      setLoading(false);
      setClick(search);
    } else {
      setLoading(false);
      setClick("");
    }
  }, [artist]);

  const handleSearch = async (e) => {
    e.preventDefault();
    setLoading(true);
    // setSearch(e.target.value);
    // console.log(search);

    if (search !== "")
      await axios
        .get(`https://rest.bandsintown.com/artists/${search}?app_id=abc`)
        .then((res) => {
          dispatch(setArtist(res.data ? res.data : null));
          setClick(search);
          setLoading(false);
          console.log(res.data);
        })
        .catch((err) => console.log(err));
    else {
      dispatch(setArtist(null));
      setLoading(false);
      setClick("");
    }
  };

  return (
    <Layout title={"Search"}>
      <Head>
        <title>Motive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form
          onSubmit={handleSearch}
          className="relative flex items-center mx-auto tracking-widest shadow-[0px_1px_5px_2px_rgba(0,0,0,0.2)] mt-20 max-w-4xl"
        >
          <input
            className="form-control pl-10 pr-14 py-3 lg:border-none rounded-none text-[#cccccc] tracking-wider"
            type="search"
            placeholder="Search Artist"
            aria-label="Search"
            onChange={(e) => dispatch(setSearch(e.target.value))}
          />
          <button type="submit">
            <BiSearch className="absolute right-5 top-4 text-[#cccccc] text-3xl" />
          </button>
        </form>
        <div className="flex flex-col justify-center items-center">
          {loading ? (
            <div className="mt-8">
              <FadeLoader />
            </div>
          ) : (
            <div>
              {artist?.error !== "Not Found" && click !== "" ? (
                <div>
                  <div className=" font-semibold tracking-widest text-gray-500 mt-8 mb-4">
                    <span>
                      Result Found for <strong> {'"' + click + '"'} </strong>
                    </span>
                  </div>
                  <Card artist={artist} />
                </div>
              ) : (
                <div className=" font-semibold tracking-widest text-gray-500 mt-8 mb-4">
                  <span>No Result Found!</span>
                  <div className="text-9xl flex items-center justify-center">
                    <HiOutlineEmojiSad />
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </main>
    </Layout>
  );
}
